### ISSUE TITLE
AttributeError: module 'llama_cpp.server' has no attribute 'app'

### ISSUE THREAD

**Issue by xysmalobia** [ChaoticByte/Eucalyptus-Chat#1]
This looks great, but I seem to have an issue with importing the llama-cpp api server. 

  File "~/Eucalyptus-Chat/api-server.py", line 22, in <module>
    uvicorn.run(server.app, host=args.host, port=args.port)
AttributeError: module 'llama_cpp.server' has no attribute 'app'

I've tried referring to app.py in llama-cpp-python/llama_cpp/server directly and then the api-server starts but throws a module error. not sure if this is a bug or something strange on my system.

**Comment by ChaoticByte** [comment]
I was able to reproduce the error. Seems like the developer of [llama-cpp-python](https://github.com/abetlen/llama-cpp-python) made an [API change](https://github.com/abetlen/llama-cpp-python/commit/9eafc4c49aa4d1dbd3cf58c73c753382a821800f) without raising the major version of the pip package.

**Comment by ChaoticByte** [comment]
should be fixed now :)

**Comment by xysmalobia** [comment]
working perfectly now, thank you!
